'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace servicefe
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Venta", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Venta
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsCreatePdfField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private agenciaIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private centroCostoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private clienteField As servicefe.Cliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private direccionEmbarqueField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private documentoReferenciaField As servicefe.DocumentoReferencia
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaEmisionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private glosaRetencionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private igvField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private informacionAdicionalField As servicefe.InformacionAdicional
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private isSOUEField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private listDetalleVentaField() As servicefe.DetalleVenta
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private montoSubTotalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private montoTotalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private montoTotalDescuentoField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroCorrelativoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroPrefacturaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroSerieField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private observacionesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private productoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoComprobanteIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoMonedaSolesField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoVentaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioInsercionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioModificacionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsCreatePdf() As Boolean
            Get
                Return Me.IsCreatePdfField
            End Get
            Set
                If (Me.IsCreatePdfField.Equals(value) <> true) Then
                    Me.IsCreatePdfField = value
                    Me.RaisePropertyChanged("IsCreatePdf")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property agenciaID() As Long
            Get
                Return Me.agenciaIDField
            End Get
            Set
                If (Me.agenciaIDField.Equals(value) <> true) Then
                    Me.agenciaIDField = value
                    Me.RaisePropertyChanged("agenciaID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property centroCosto() As String
            Get
                Return Me.centroCostoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.centroCostoField, value) <> true) Then
                    Me.centroCostoField = value
                    Me.RaisePropertyChanged("centroCosto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cliente() As servicefe.Cliente
            Get
                Return Me.clienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.clienteField, value) <> true) Then
                    Me.clienteField = value
                    Me.RaisePropertyChanged("cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property direccionEmbarque() As String
            Get
                Return Me.direccionEmbarqueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.direccionEmbarqueField, value) <> true) Then
                    Me.direccionEmbarqueField = value
                    Me.RaisePropertyChanged("direccionEmbarque")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property documentoReferencia() As servicefe.DocumentoReferencia
            Get
                Return Me.documentoReferenciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.documentoReferenciaField, value) <> true) Then
                    Me.documentoReferenciaField = value
                    Me.RaisePropertyChanged("documentoReferencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fechaEmision() As String
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fechaEmisionField, value) <> true) Then
                    Me.fechaEmisionField = value
                    Me.RaisePropertyChanged("fechaEmision")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property glosaRetencion() As String
            Get
                Return Me.glosaRetencionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.glosaRetencionField, value) <> true) Then
                    Me.glosaRetencionField = value
                    Me.RaisePropertyChanged("glosaRetencion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property igv() As Double
            Get
                Return Me.igvField
            End Get
            Set
                If (Me.igvField.Equals(value) <> true) Then
                    Me.igvField = value
                    Me.RaisePropertyChanged("igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property informacionAdicional() As servicefe.InformacionAdicional
            Get
                Return Me.informacionAdicionalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.informacionAdicionalField, value) <> true) Then
                    Me.informacionAdicionalField = value
                    Me.RaisePropertyChanged("informacionAdicional")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property isSOUE() As Boolean
            Get
                Return Me.isSOUEField
            End Get
            Set
                If (Me.isSOUEField.Equals(value) <> true) Then
                    Me.isSOUEField = value
                    Me.RaisePropertyChanged("isSOUE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property listDetalleVenta() As servicefe.DetalleVenta()
            Get
                Return Me.listDetalleVentaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.listDetalleVentaField, value) <> true) Then
                    Me.listDetalleVentaField = value
                    Me.RaisePropertyChanged("listDetalleVenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property montoSubTotal() As Double
            Get
                Return Me.montoSubTotalField
            End Get
            Set
                If (Me.montoSubTotalField.Equals(value) <> true) Then
                    Me.montoSubTotalField = value
                    Me.RaisePropertyChanged("montoSubTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property montoTotal() As Double
            Get
                Return Me.montoTotalField
            End Get
            Set
                If (Me.montoTotalField.Equals(value) <> true) Then
                    Me.montoTotalField = value
                    Me.RaisePropertyChanged("montoTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property montoTotalDescuento() As Double
            Get
                Return Me.montoTotalDescuentoField
            End Get
            Set
                If (Me.montoTotalDescuentoField.Equals(value) <> true) Then
                    Me.montoTotalDescuentoField = value
                    Me.RaisePropertyChanged("montoTotalDescuento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroCorrelativo() As String
            Get
                Return Me.numeroCorrelativoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroCorrelativoField, value) <> true) Then
                    Me.numeroCorrelativoField = value
                    Me.RaisePropertyChanged("numeroCorrelativo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroPrefactura() As String
            Get
                Return Me.numeroPrefacturaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroPrefacturaField, value) <> true) Then
                    Me.numeroPrefacturaField = value
                    Me.RaisePropertyChanged("numeroPrefactura")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroSerie() As String
            Get
                Return Me.numeroSerieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroSerieField, value) <> true) Then
                    Me.numeroSerieField = value
                    Me.RaisePropertyChanged("numeroSerie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property observaciones() As String
            Get
                Return Me.observacionesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.observacionesField, value) <> true) Then
                    Me.observacionesField = value
                    Me.RaisePropertyChanged("observaciones")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property producto() As String
            Get
                Return Me.productoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.productoField, value) <> true) Then
                    Me.productoField = value
                    Me.RaisePropertyChanged("producto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoComprobanteID() As String
            Get
                Return Me.tipoComprobanteIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tipoComprobanteIDField, value) <> true) Then
                    Me.tipoComprobanteIDField = value
                    Me.RaisePropertyChanged("tipoComprobanteID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoMonedaSoles() As Boolean
            Get
                Return Me.tipoMonedaSolesField
            End Get
            Set
                If (Me.tipoMonedaSolesField.Equals(value) <> true) Then
                    Me.tipoMonedaSolesField = value
                    Me.RaisePropertyChanged("tipoMonedaSoles")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoVenta() As Integer
            Get
                Return Me.tipoVentaField
            End Get
            Set
                If (Me.tipoVentaField.Equals(value) <> true) Then
                    Me.tipoVentaField = value
                    Me.RaisePropertyChanged("tipoVenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioID() As Long
            Get
                Return Me.usuarioIDField
            End Get
            Set
                If (Me.usuarioIDField.Equals(value) <> true) Then
                    Me.usuarioIDField = value
                    Me.RaisePropertyChanged("usuarioID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioInsercion() As String
            Get
                Return Me.usuarioInsercionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioInsercionField, value) <> true) Then
                    Me.usuarioInsercionField = value
                    Me.RaisePropertyChanged("usuarioInsercion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioModificacion() As String
            Get
                Return Me.usuarioModificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioModificacionField, value) <> true) Then
                    Me.usuarioModificacionField = value
                    Me.RaisePropertyChanged("usuarioModificacion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cliente", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cliente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private direccionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoDocumentoIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.direccionField, value) <> true) Then
                    Me.direccionField = value
                    Me.RaisePropertyChanged("direccion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombres() As String
            Get
                Return Me.nombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombresField, value) <> true) Then
                    Me.nombresField = value
                    Me.RaisePropertyChanged("nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroDocumentoField, value) <> true) Then
                    Me.numeroDocumentoField = value
                    Me.RaisePropertyChanged("numeroDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoDocumentoID() As String
            Get
                Return Me.tipoDocumentoIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tipoDocumentoIDField, value) <> true) Then
                    Me.tipoDocumentoIDField = value
                    Me.RaisePropertyChanged("tipoDocumentoID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DocumentoReferencia", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DocumentoReferencia
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoComprobanteField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaDocumento() As String
            Get
                Return Me.FechaDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaDocumentoField, value) <> true) Then
                    Me.FechaDocumentoField = value
                    Me.RaisePropertyChanged("FechaDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroDocumento() As String
            Get
                Return Me.NumeroDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroDocumentoField, value) <> true) Then
                    Me.NumeroDocumentoField = value
                    Me.RaisePropertyChanged("NumeroDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoComprobante() As String
            Get
                Return Me.TipoComprobanteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoComprobanteField, value) <> true) Then
                    Me.TipoComprobanteField = value
                    Me.RaisePropertyChanged("TipoComprobante")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InformacionAdicional", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InformacionAdicional
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PropiedadesAdicionalesField() As servicefe.InformacionAdicional.PropiedadAdicional
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalesMonedaAdicionalField() As servicefe.InformacionAdicional.TotalMonedaAdicional
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PropiedadesAdicionales() As servicefe.InformacionAdicional.PropiedadAdicional()
            Get
                Return Me.PropiedadesAdicionalesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PropiedadesAdicionalesField, value) <> true) Then
                    Me.PropiedadesAdicionalesField = value
                    Me.RaisePropertyChanged("PropiedadesAdicionales")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalesMonedaAdicional() As servicefe.InformacionAdicional.TotalMonedaAdicional()
            Get
                Return Me.TotalesMonedaAdicionalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TotalesMonedaAdicionalField, value) <> true) Then
                    Me.TotalesMonedaAdicionalField = value
                    Me.RaisePropertyChanged("TotalesMonedaAdicional")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="InformacionAdicional.PropiedadAdicional", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
         System.SerializableAttribute()>  _
        Partial Public Class PropiedadAdicional
            Inherits Object
            Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
            
            <System.NonSerializedAttribute()>  _
            Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
            
            <System.Runtime.Serialization.OptionalFieldAttribute()>  _
            Private codigoField As String
            
            <System.Runtime.Serialization.OptionalFieldAttribute()>  _
            Private nombreField As String
            
            <System.Runtime.Serialization.OptionalFieldAttribute()>  _
            Private valueField As String
            
            Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
                Get
                    Return Me.extensionDataField
                End Get
                Set
                    Me.extensionDataField = value
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute()>  _
            Public Property codigo() As String
                Get
                    Return Me.codigoField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.codigoField, value) <> true) Then
                        Me.codigoField = value
                        Me.RaisePropertyChanged("codigo")
                    End If
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute()>  _
            Public Property nombre() As String
                Get
                    Return Me.nombreField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.nombreField, value) <> true) Then
                        Me.nombreField = value
                        Me.RaisePropertyChanged("nombre")
                    End If
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute()>  _
            Public Property value() As String
                Get
                    Return Me.valueField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.valueField, value) <> true) Then
                        Me.valueField = value
                        Me.RaisePropertyChanged("value")
                    End If
                End Set
            End Property
            
            Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
            
            Protected Sub RaisePropertyChanged(ByVal propertyName As String)
                Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
                If (Not (propertyChanged) Is Nothing) Then
                    propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
                End If
            End Sub
        End Class
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="InformacionAdicional.TotalMonedaAdicional", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
         System.SerializableAttribute()>  _
        Partial Public Class TotalMonedaAdicional
            Inherits Object
            Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
            
            <System.NonSerializedAttribute()>  _
            Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
            
            <System.Runtime.Serialization.OptionalFieldAttribute()>  _
            Private codigoField As String
            
            <System.Runtime.Serialization.OptionalFieldAttribute()>  _
            Private nombreField As String
            
            <System.Runtime.Serialization.OptionalFieldAttribute()>  _
            Private valorField As String
            
            Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
                Get
                    Return Me.extensionDataField
                End Get
                Set
                    Me.extensionDataField = value
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute()>  _
            Public Property codigo() As String
                Get
                    Return Me.codigoField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.codigoField, value) <> true) Then
                        Me.codigoField = value
                        Me.RaisePropertyChanged("codigo")
                    End If
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute()>  _
            Public Property nombre() As String
                Get
                    Return Me.nombreField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.nombreField, value) <> true) Then
                        Me.nombreField = value
                        Me.RaisePropertyChanged("nombre")
                    End If
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute()>  _
            Public Property valor() As String
                Get
                    Return Me.valorField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.valorField, value) <> true) Then
                        Me.valorField = value
                        Me.RaisePropertyChanged("valor")
                    End If
                End Set
            End Property
            
            Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
            
            Protected Sub RaisePropertyChanged(ByVal propertyName As String)
                Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
                If (Not (propertyChanged) Is Nothing) Then
                    propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
                End If
            End Sub
        End Class
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DetalleVenta", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DetalleVenta
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private bultosField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cantidadField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoAfectacionIgvField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoProductoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoTipoPrecioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private igvField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private itemField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private porcentajeIgvField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tarifaField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private totalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private unidadMedidaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private valorUnitarioField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property bultos() As Integer
            Get
                Return Me.bultosField
            End Get
            Set
                If (Me.bultosField.Equals(value) <> true) Then
                    Me.bultosField = value
                    Me.RaisePropertyChanged("bultos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cantidad() As Double
            Get
                Return Me.cantidadField
            End Get
            Set
                If (Me.cantidadField.Equals(value) <> true) Then
                    Me.cantidadField = value
                    Me.RaisePropertyChanged("cantidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigoAfectacionIgv() As String
            Get
                Return Me.codigoAfectacionIgvField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codigoAfectacionIgvField, value) <> true) Then
                    Me.codigoAfectacionIgvField = value
                    Me.RaisePropertyChanged("codigoAfectacionIgv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigoProducto() As String
            Get
                Return Me.codigoProductoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codigoProductoField, value) <> true) Then
                    Me.codigoProductoField = value
                    Me.RaisePropertyChanged("codigoProducto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigoTipoPrecio() As String
            Get
                Return Me.codigoTipoPrecioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codigoTipoPrecioField, value) <> true) Then
                    Me.codigoTipoPrecioField = value
                    Me.RaisePropertyChanged("codigoTipoPrecio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descripcionField, value) <> true) Then
                    Me.descripcionField = value
                    Me.RaisePropertyChanged("descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property igv() As Double
            Get
                Return Me.igvField
            End Get
            Set
                If (Me.igvField.Equals(value) <> true) Then
                    Me.igvField = value
                    Me.RaisePropertyChanged("igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property item() As Integer
            Get
                Return Me.itemField
            End Get
            Set
                If (Me.itemField.Equals(value) <> true) Then
                    Me.itemField = value
                    Me.RaisePropertyChanged("item")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property porcentajeIgv() As Double
            Get
                Return Me.porcentajeIgvField
            End Get
            Set
                If (Me.porcentajeIgvField.Equals(value) <> true) Then
                    Me.porcentajeIgvField = value
                    Me.RaisePropertyChanged("porcentajeIgv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tarifa() As Double
            Get
                Return Me.tarifaField
            End Get
            Set
                If (Me.tarifaField.Equals(value) <> true) Then
                    Me.tarifaField = value
                    Me.RaisePropertyChanged("tarifa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property total() As Double
            Get
                Return Me.totalField
            End Get
            Set
                If (Me.totalField.Equals(value) <> true) Then
                    Me.totalField = value
                    Me.RaisePropertyChanged("total")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property unidadMedida() As String
            Get
                Return Me.unidadMedidaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.unidadMedidaField, value) <> true) Then
                    Me.unidadMedidaField = value
                    Me.RaisePropertyChanged("unidadMedida")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property valorUnitario() As Double
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                If (Me.valorUnitarioField.Equals(value) <> true) Then
                    Me.valorUnitarioField = value
                    Me.RaisePropertyChanged("valorUnitario")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Result", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Util"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsCorrectField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private barcodeField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private barcode_QRField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private listDetalleVentaField() As servicefe.DetalleVenta
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pdfField() As Byte
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsCorrect() As Boolean
            Get
                Return Me.IsCorrectField
            End Get
            Set
                If (Me.IsCorrectField.Equals(value) <> true) Then
                    Me.IsCorrectField = value
                    Me.RaisePropertyChanged("IsCorrect")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property barcode() As Byte()
            Get
                Return Me.barcodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.barcodeField, value) <> true) Then
                    Me.barcodeField = value
                    Me.RaisePropertyChanged("barcode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property barcode_QR() As Byte()
            Get
                Return Me.barcode_QRField
            End Get
            Set
                If (Object.ReferenceEquals(Me.barcode_QRField, value) <> true) Then
                    Me.barcode_QRField = value
                    Me.RaisePropertyChanged("barcode_QR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property listDetalleVenta() As servicefe.DetalleVenta()
            Get
                Return Me.listDetalleVentaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.listDetalleVentaField, value) <> true) Then
                    Me.listDetalleVentaField = value
                    Me.RaisePropertyChanged("listDetalleVenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property pdf() As Byte()
            Get
                Return Me.pdfField
            End Get
            Set
                If (Object.ReferenceEquals(Me.pdfField, value) <> true) Then
                    Me.pdfField = value
                    Me.RaisePropertyChanged("pdf")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Nota", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Nota
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private agenciaIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private clienteField As servicefe.Cliente
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoTipoNotaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descripcionSustentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descripcionTipoNotaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private documentoReferenciaField As servicefe.DocumentoReferencia
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaEmisionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private igvField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private informacionAdicionalField As servicefe.InformacionAdicional
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroCorrelativoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroSerieField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private subtotalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoComprobanteIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoMonedaSolesField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoVentaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private totalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioInsercionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioModificacionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property agenciaID() As Long
            Get
                Return Me.agenciaIDField
            End Get
            Set
                If (Me.agenciaIDField.Equals(value) <> true) Then
                    Me.agenciaIDField = value
                    Me.RaisePropertyChanged("agenciaID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cliente() As servicefe.Cliente
            Get
                Return Me.clienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.clienteField, value) <> true) Then
                    Me.clienteField = value
                    Me.RaisePropertyChanged("cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigoTipoNota() As String
            Get
                Return Me.codigoTipoNotaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codigoTipoNotaField, value) <> true) Then
                    Me.codigoTipoNotaField = value
                    Me.RaisePropertyChanged("codigoTipoNota")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descripcionSustento() As String
            Get
                Return Me.descripcionSustentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descripcionSustentoField, value) <> true) Then
                    Me.descripcionSustentoField = value
                    Me.RaisePropertyChanged("descripcionSustento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descripcionTipoNota() As String
            Get
                Return Me.descripcionTipoNotaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descripcionTipoNotaField, value) <> true) Then
                    Me.descripcionTipoNotaField = value
                    Me.RaisePropertyChanged("descripcionTipoNota")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property documentoReferencia() As servicefe.DocumentoReferencia
            Get
                Return Me.documentoReferenciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.documentoReferenciaField, value) <> true) Then
                    Me.documentoReferenciaField = value
                    Me.RaisePropertyChanged("documentoReferencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fechaEmision() As String
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fechaEmisionField, value) <> true) Then
                    Me.fechaEmisionField = value
                    Me.RaisePropertyChanged("fechaEmision")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property igv() As Double
            Get
                Return Me.igvField
            End Get
            Set
                If (Me.igvField.Equals(value) <> true) Then
                    Me.igvField = value
                    Me.RaisePropertyChanged("igv")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property informacionAdicional() As servicefe.InformacionAdicional
            Get
                Return Me.informacionAdicionalField
            End Get
            Set
                If (Object.ReferenceEquals(Me.informacionAdicionalField, value) <> true) Then
                    Me.informacionAdicionalField = value
                    Me.RaisePropertyChanged("informacionAdicional")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroCorrelativo() As String
            Get
                Return Me.numeroCorrelativoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroCorrelativoField, value) <> true) Then
                    Me.numeroCorrelativoField = value
                    Me.RaisePropertyChanged("numeroCorrelativo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroSerie() As String
            Get
                Return Me.numeroSerieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroSerieField, value) <> true) Then
                    Me.numeroSerieField = value
                    Me.RaisePropertyChanged("numeroSerie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property subtotal() As Double
            Get
                Return Me.subtotalField
            End Get
            Set
                If (Me.subtotalField.Equals(value) <> true) Then
                    Me.subtotalField = value
                    Me.RaisePropertyChanged("subtotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoComprobanteID() As String
            Get
                Return Me.tipoComprobanteIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tipoComprobanteIDField, value) <> true) Then
                    Me.tipoComprobanteIDField = value
                    Me.RaisePropertyChanged("tipoComprobanteID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoMonedaSoles() As Boolean
            Get
                Return Me.tipoMonedaSolesField
            End Get
            Set
                If (Me.tipoMonedaSolesField.Equals(value) <> true) Then
                    Me.tipoMonedaSolesField = value
                    Me.RaisePropertyChanged("tipoMonedaSoles")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoVenta() As Integer
            Get
                Return Me.tipoVentaField
            End Get
            Set
                If (Me.tipoVentaField.Equals(value) <> true) Then
                    Me.tipoVentaField = value
                    Me.RaisePropertyChanged("tipoVenta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property total() As Double
            Get
                Return Me.totalField
            End Get
            Set
                If (Me.totalField.Equals(value) <> true) Then
                    Me.totalField = value
                    Me.RaisePropertyChanged("total")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioID() As Long
            Get
                Return Me.usuarioIDField
            End Get
            Set
                If (Me.usuarioIDField.Equals(value) <> true) Then
                    Me.usuarioIDField = value
                    Me.RaisePropertyChanged("usuarioID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioInsercion() As String
            Get
                Return Me.usuarioInsercionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioInsercionField, value) <> true) Then
                    Me.usuarioInsercionField = value
                    Me.RaisePropertyChanged("usuarioInsercion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioModificacion() As String
            Get
                Return Me.usuarioModificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioModificacionField, value) <> true) Then
                    Me.usuarioModificacionField = value
                    Me.RaisePropertyChanged("usuarioModificacion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DocumentoBaja", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DocumentoBaja
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private agenciaIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descripcionMotivoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaEmisionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroCorrelativoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroSerieField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private tipoDocumentoIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioIDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioInsercionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private usuarioModificacionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property agenciaID() As Long
            Get
                Return Me.agenciaIDField
            End Get
            Set
                If (Me.agenciaIDField.Equals(value) <> true) Then
                    Me.agenciaIDField = value
                    Me.RaisePropertyChanged("agenciaID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property descripcionMotivo() As String
            Get
                Return Me.descripcionMotivoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descripcionMotivoField, value) <> true) Then
                    Me.descripcionMotivoField = value
                    Me.RaisePropertyChanged("descripcionMotivo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fechaEmision() As String
            Get
                Return Me.fechaEmisionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fechaEmisionField, value) <> true) Then
                    Me.fechaEmisionField = value
                    Me.RaisePropertyChanged("fechaEmision")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroCorrelativo() As String
            Get
                Return Me.numeroCorrelativoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroCorrelativoField, value) <> true) Then
                    Me.numeroCorrelativoField = value
                    Me.RaisePropertyChanged("numeroCorrelativo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroSerie() As String
            Get
                Return Me.numeroSerieField
            End Get
            Set
                If (Object.ReferenceEquals(Me.numeroSerieField, value) <> true) Then
                    Me.numeroSerieField = value
                    Me.RaisePropertyChanged("numeroSerie")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tipoDocumentoID() As String
            Get
                Return Me.tipoDocumentoIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.tipoDocumentoIDField, value) <> true) Then
                    Me.tipoDocumentoIDField = value
                    Me.RaisePropertyChanged("tipoDocumentoID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioID() As Long
            Get
                Return Me.usuarioIDField
            End Get
            Set
                If (Me.usuarioIDField.Equals(value) <> true) Then
                    Me.usuarioIDField = value
                    Me.RaisePropertyChanged("usuarioID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioInsercion() As String
            Get
                Return Me.usuarioInsercionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioInsercionField, value) <> true) Then
                    Me.usuarioInsercionField = value
                    Me.RaisePropertyChanged("usuarioInsercion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property usuarioModificacion() As String
            Get
                Return Me.usuarioModificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.usuarioModificacionField, value) <> true) Then
                    Me.usuarioModificacionField = value
                    Me.RaisePropertyChanged("usuarioModificacion")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DocumentCDR", [Namespace]:="http://schemas.datacontract.org/2004/07/FEService.Input"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DocumentCDR
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idEnvioDatoField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private isResumenField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ticketField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                If (Object.ReferenceEquals(Me.idField, value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property idEnvioDato() As Long
            Get
                Return Me.idEnvioDatoField
            End Get
            Set
                If (Me.idEnvioDatoField.Equals(value) <> true) Then
                    Me.idEnvioDatoField = value
                    Me.RaisePropertyChanged("idEnvioDato")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property isResumen() As Boolean
            Get
                Return Me.isResumenField
            End Get
            Set
                If (Me.isResumenField.Equals(value) <> true) Then
                    Me.isResumenField = value
                    Me.RaisePropertyChanged("isResumen")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ticket() As String
            Get
                Return Me.ticketField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ticketField, value) <> true) Then
                    Me.ticketField = value
                    Me.RaisePropertyChanged("ticket")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="servicefe.ITepsafeservice")>  _
    Public Interface ITepsafeservice
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setVenta", ReplyAction:="http://tempuri.org/ITepsafeservice/setVentaResponse")>  _
        Function setVenta(ByVal token As String, ByVal venta As servicefe.Venta) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setNota", ReplyAction:="http://tempuri.org/ITepsafeservice/setNotaResponse")>  _
        Function setNota(ByVal token As String, ByVal notaCreditoDebito As servicefe.Nota) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setBajas", ReplyAction:="http://tempuri.org/ITepsafeservice/setBajasResponse")>  _
        Function setBajas(ByVal token As String, ByVal fechaEmisionComprobantes As String) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setResumenes", ReplyAction:="http://tempuri.org/ITepsafeservice/setResumenesResponse")>  _
        Function setResumenes(ByVal token As String, ByVal fechaEmisionComprobantes As String) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setUpdateStatusCDR", ReplyAction:="http://tempuri.org/ITepsafeservice/setUpdateStatusCDRResponse")>  _
        Function setUpdateStatusCDR(ByVal token As String) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setBajaDocumento", ReplyAction:="http://tempuri.org/ITepsafeservice/setBajaDocumentoResponse")>  _
        Function setBajaDocumento(ByVal token As String, ByVal documentoBaja As servicefe.DocumentoBaja) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setNotaVenta", ReplyAction:="http://tempuri.org/ITepsafeservice/setNotaVentaResponse")>  _
        Function setNotaVenta(ByVal token As String, ByVal nota As servicefe.Nota, ByVal venta As servicefe.Venta) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setEnviarComprobantesSunat", ReplyAction:="http://tempuri.org/ITepsafeservice/setEnviarComprobantesSunatResponse")>  _
        Function setEnviarComprobantesSunat(ByVal token As String) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/getRepresentacionImpresa", ReplyAction:="http://tempuri.org/ITepsafeservice/getRepresentacionImpresaResponse")>  _
        Function getRepresentacionImpresa(ByVal token As String, ByVal isPasajes As Boolean, ByVal tipoComprobante As String, ByVal serie As String, ByVal correlativo As String) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/searchOperacionesBySendMail", ReplyAction:="http://tempuri.org/ITepsafeservice/searchOperacionesBySendMailResponse")>  _
        Function searchOperacionesBySendMail(ByVal token As String) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setUpdatePdf", ReplyAction:="http://tempuri.org/ITepsafeservice/setUpdatePdfResponse")>  _
        Sub setUpdatePdf()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/buscarDetalleComprobante", ReplyAction:="http://tempuri.org/ITepsafeservice/buscarDetalleComprobanteResponse")>  _
        Function buscarDetalleComprobante(ByVal token As String, ByVal tipoComprobante As String, ByVal serie As String, ByVal correlativo As String) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/setConsultarCDR", ReplyAction:="http://tempuri.org/ITepsafeservice/setConsultarCDRResponse")>  _
        Function setConsultarCDR(ByVal token As String, ByVal documentCDR As servicefe.DocumentCDR) As servicefe.Result
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITepsafeservice/searchOperacionesByConfirmar", ReplyAction:="http://tempuri.org/ITepsafeservice/searchOperacionesByConfirmarResponse")>  _
        Function searchOperacionesByConfirmar(ByVal token As String) As servicefe.Result
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITepsafeserviceChannel
        Inherits servicefe.ITepsafeservice, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TepsafeserviceClient
        Inherits System.ServiceModel.ClientBase(Of servicefe.ITepsafeservice)
        Implements servicefe.ITepsafeservice
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function setVenta(ByVal token As String, ByVal venta As servicefe.Venta) As servicefe.Result Implements servicefe.ITepsafeservice.setVenta
            Return MyBase.Channel.setVenta(token, venta)
        End Function
        
        Public Function setNota(ByVal token As String, ByVal notaCreditoDebito As servicefe.Nota) As servicefe.Result Implements servicefe.ITepsafeservice.setNota
            Return MyBase.Channel.setNota(token, notaCreditoDebito)
        End Function
        
        Public Function setBajas(ByVal token As String, ByVal fechaEmisionComprobantes As String) As servicefe.Result Implements servicefe.ITepsafeservice.setBajas
            Return MyBase.Channel.setBajas(token, fechaEmisionComprobantes)
        End Function
        
        Public Function setResumenes(ByVal token As String, ByVal fechaEmisionComprobantes As String) As servicefe.Result Implements servicefe.ITepsafeservice.setResumenes
            Return MyBase.Channel.setResumenes(token, fechaEmisionComprobantes)
        End Function
        
        Public Function setUpdateStatusCDR(ByVal token As String) As servicefe.Result Implements servicefe.ITepsafeservice.setUpdateStatusCDR
            Return MyBase.Channel.setUpdateStatusCDR(token)
        End Function
        
        Public Function setBajaDocumento(ByVal token As String, ByVal documentoBaja As servicefe.DocumentoBaja) As servicefe.Result Implements servicefe.ITepsafeservice.setBajaDocumento
            Return MyBase.Channel.setBajaDocumento(token, documentoBaja)
        End Function
        
        Public Function setNotaVenta(ByVal token As String, ByVal nota As servicefe.Nota, ByVal venta As servicefe.Venta) As servicefe.Result Implements servicefe.ITepsafeservice.setNotaVenta
            Return MyBase.Channel.setNotaVenta(token, nota, venta)
        End Function
        
        Public Function setEnviarComprobantesSunat(ByVal token As String) As servicefe.Result Implements servicefe.ITepsafeservice.setEnviarComprobantesSunat
            Return MyBase.Channel.setEnviarComprobantesSunat(token)
        End Function
        
        Public Function getRepresentacionImpresa(ByVal token As String, ByVal isPasajes As Boolean, ByVal tipoComprobante As String, ByVal serie As String, ByVal correlativo As String) As servicefe.Result Implements servicefe.ITepsafeservice.getRepresentacionImpresa
            Return MyBase.Channel.getRepresentacionImpresa(token, isPasajes, tipoComprobante, serie, correlativo)
        End Function
        
        Public Function searchOperacionesBySendMail(ByVal token As String) As servicefe.Result Implements servicefe.ITepsafeservice.searchOperacionesBySendMail
            Return MyBase.Channel.searchOperacionesBySendMail(token)
        End Function
        
        Public Sub setUpdatePdf() Implements servicefe.ITepsafeservice.setUpdatePdf
            MyBase.Channel.setUpdatePdf
        End Sub
        
        Public Function buscarDetalleComprobante(ByVal token As String, ByVal tipoComprobante As String, ByVal serie As String, ByVal correlativo As String) As servicefe.Result Implements servicefe.ITepsafeservice.buscarDetalleComprobante
            Return MyBase.Channel.buscarDetalleComprobante(token, tipoComprobante, serie, correlativo)
        End Function
        
        Public Function setConsultarCDR(ByVal token As String, ByVal documentCDR As servicefe.DocumentCDR) As servicefe.Result Implements servicefe.ITepsafeservice.setConsultarCDR
            Return MyBase.Channel.setConsultarCDR(token, documentCDR)
        End Function
        
        Public Function searchOperacionesByConfirmar(ByVal token As String) As servicefe.Result Implements servicefe.ITepsafeservice.searchOperacionesByConfirmar
            Return MyBase.Channel.searchOperacionesByConfirmar(token)
        End Function
    End Class
End Namespace
